-- Book Manager 初期スキーマ
CREATE TABLE IF NOT EXISTS book(
    -- 書籍ID（数値主キー）。アプリ層では IntId を採用。
    book_id int primary key generated by default as identity,
    -- 書籍名（必須）
    book_name varchar(64) not null,
    -- あらすじ（簡易説明）
    book_outline varchar(128) not null,
    -- 初版の出版日（ローカル日付）
    published_at date not null,
    -- 筆者名
    author varchar(32) not null,
    -- 蔵書日（登録日時・デフォルト現在時刻）。DB 側でデフォルト付与
    deposited_at timestamp with time zone not null default current_timestamp,
    -- ISBN（ハイフン付きも許容するため最大17文字）。一意制約で重複登録を防止
    isbn varchar(17) not null unique
);
-- 著者名での検索最適化用インデックス（部分一致などはアプリ側で別途対応）
CREATE INDEX ON book(author);

-- 権限レベルを表現する型（値の追加は ALTER TYPE で行うこと）
CREATE TYPE ACCOUNT_LEVEL AS ENUM(
    'General',
    'Admin'
);

CREATE TABLE IF NOT EXISTS account(
    -- アカウントID（UUID主キー）
    account_id uuid primary key,
    -- 表示名
    name varchar(32) not null,
    -- メールアドレス（RFCを考慮し最大384）。
    email varchar(384) not null unique,
    -- パスワードハッシュ
    hashed_password varchar(256) not null,
    -- 権限レベル（ACCOUNT_LEVEL ENUM）
    account_level ACCOUNT_LEVEL not null,
    -- 作成日時（デフォルト現在時刻）
    created_at timestamp with time zone not null default current_timestamp,
    -- 更新日時（デフォルト現在時刻。アプリ側で更新時に更新推奨）
    updated_at timestamp with time zone not null default current_timestamp
);


CREATE TABLE IF NOT EXISTS rental(
    -- 貸出ID（UUID主キー）
    rent_id uuid primary key,
    -- 書籍ID（book.book_id を参照）。書籍削除は RESTRICT、ID更新は CASCADE
    book_id int not null references book(book_id) on delete restrict on update cascade,
    -- 利用者（account.account_id を参照）。ユーザ削除は CASCADE、ID更新は CASCADE
    user_id uuid not null references account(account_id) on delete cascade on update cascade,

    -- 貸出日時（必須）。貸出開始のタイムスタンプ
    rental_at timestamp with time zone not null,
    -- 返却日時（返却済みの場合のみ値が入る）
    returned_at timestamp with time zone null,
    -- 返却期限（必須）
    return_deadline timestamp with time zone not null
);
-- 外部キー列に対するインデックス（結合・検索の高速化）
CREATE INDEX ON rental(book_id);
CREATE INDEX ON rental(user_id);
-- 同一書籍の同時重複貸出を防ぐための部分ユニーク制約（未返却行のみを対象）
CREATE UNIQUE INDEX ON rental(book_id) WHERE returned_at IS NULL;